/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['169_India_Edited']: THREE.Mesh
  }
  materials: {
    ['initialShadingGroup.001']: THREE.MeshBasicMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/dmodel.glb') as GLTFResult
  materials['initialShadingGroup.001'].side = 0
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['169_India_Edited'].geometry} material={materials['initialShadingGroup.001']} />
    </group>
  )
}

useGLTF.preload('/dmodel.glb')
